package test.mybatis.mapper;

import java.util.List;
import test.mybatis.pojo.Shelf;

public interface ShelfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shelf
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shelf
     *
     * @mbggenerated
     */
    int insert(Shelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shelf
     *
     * @mbggenerated
     */
    Shelf selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shelf
     *
     * @mbggenerated
     */
    List<Shelf> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shelf
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shelf record);
}