package test.mybatis.mapper;

import java.util.List;
import test.mybatis.pojo.TsBPjzcTSpSxrmd;

public interface TsBPjzcTSpSxrmdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_B_PJZC_T_SP_SXRMD
     *
     * @mbggenerated
     */
    int insert(TsBPjzcTSpSxrmd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_B_PJZC_T_SP_SXRMD
     *
     * @mbggenerated
     */
    List<TsBPjzcTSpSxrmd> selectAll();
}