package test.mybatis.mapper;

import java.util.List;
import test.mybatis.pojo.TsC500035JbxxZtsbFrjc;

public interface TsC500035JbxxZtsbFrjcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_C500035_JBXX_ZTSB_FRJC
     *
     * @mbg.generated
     */
    int insert(TsC500035JbxxZtsbFrjc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_C500035_JBXX_ZTSB_FRJC
     *
     * @mbg.generated
     */
    List<TsC500035JbxxZtsbFrjc> selectAll();
}