package test.mybatis.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TsBPjzcTSpSxrmd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.AJBS
     *
     * @mbggenerated
     */
    private String ajbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.AHQC
     *
     * @mbggenerated
     */
    private String ahqc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.FYDM
     *
     * @mbggenerated
     */
    private String fydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.FYMC
     *
     * @mbggenerated
     */
    private String fymc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.GSBD
     *
     * @mbggenerated
     */
    private BigDecimal gsbd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.LARQ
     *
     * @mbggenerated
     */
    private Date larq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.BZXRLX
     *
     * @mbggenerated
     */
    private Integer bzxrlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.BZXRLXMC
     *
     * @mbggenerated
     */
    private String bzxrlxmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.DSRID
     *
     * @mbggenerated
     */
    private String dsrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.XM
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.XBBM
     *
     * @mbggenerated
     */
    private Integer xbbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.XBMC
     *
     * @mbggenerated
     */
    private String xbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.SFZJHM
     *
     * @mbggenerated
     */
    private String sfzjhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZPDZ
     *
     * @mbggenerated
     */
    private String zpdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.MZBM
     *
     * @mbggenerated
     */
    private String mzbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.MZMC
     *
     * @mbggenerated
     */
    private String mzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZZMMBM
     *
     * @mbggenerated
     */
    private String zzmmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZZMMMC
     *
     * @mbggenerated
     */
    private String zzmmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.DZ
     *
     * @mbggenerated
     */
    private String dz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.DWMC
     *
     * @mbggenerated
     */
    private String dwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.SFRDZXWY
     *
     * @mbggenerated
     */
    private Integer sfrdzxwy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.RDZXDZ
     *
     * @mbggenerated
     */
    private String rdzxdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.SFXZGXF
     *
     * @mbggenerated
     */
    private Integer sfxzgxf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.SFXZGXFMC
     *
     * @mbggenerated
     */
    private String sfxzgxfmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZZJGDM
     *
     * @mbggenerated
     */
    private String zzjgdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZSD
     *
     * @mbggenerated
     */
    private String zsd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.TZRMC
     *
     * @mbggenerated
     */
    private String tzrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.CYM
     *
     * @mbggenerated
     */
    private String cym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.CJSJ
     *
     * @mbggenerated
     */
    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZT
     *
     * @mbggenerated
     */
    private Integer zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.SYS_TIME
     *
     * @mbggenerated
     */
    private Date sysTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.CJRBM
     *
     * @mbggenerated
     */
    private String cjrbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.CJRMC
     *
     * @mbggenerated
     */
    private String cjrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.SCRBM
     *
     * @mbggenerated
     */
    private String scrbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.SCRMC
     *
     * @mbggenerated
     */
    private String scrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZTMC
     *
     * @mbggenerated
     */
    private String ztmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.READFLAG
     *
     * @mbggenerated
     */
    private Integer readflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.LX
     *
     * @mbggenerated
     */
    private Integer lx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.LXMC
     *
     * @mbggenerated
     */
    private String lxmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZXCJCS
     *
     * @mbggenerated
     */
    private Integer zxcjcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZXCJCSMC
     *
     * @mbggenerated
     */
    private String zxcjcsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.JLID
     *
     * @mbggenerated
     */
    private String jlid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.JSCRBM
     *
     * @mbggenerated
     */
    private String jscrbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.JSCRMC
     *
     * @mbggenerated
     */
    private String jscrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.YSCRBM
     *
     * @mbggenerated
     */
    private String yscrbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.YSCRMC
     *
     * @mbggenerated
     */
    private String yscrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.FDDBR
     *
     * @mbggenerated
     */
    private String fddbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.XZSTARTDATE
     *
     * @mbggenerated
     */
    private Date xzstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.XZENDDATE
     *
     * @mbggenerated
     */
    private Date xzenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.XZJCDATE
     *
     * @mbggenerated
     */
    private Date xzjcdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZXYJWH
     *
     * @mbggenerated
     */
    private String zxyjwh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZXYJWHDW
     *
     * @mbggenerated
     */
    private String zxyjwhdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.LXQK
     *
     * @mbggenerated
     */
    private Integer lxqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.LXQKMC
     *
     * @mbggenerated
     */
    private String lxqkmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.JTQX
     *
     * @mbggenerated
     */
    private String jtqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.NL
     *
     * @mbggenerated
     */
    private Integer nl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.AGE
     *
     * @mbggenerated
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.DYID
     *
     * @mbggenerated
     */
    private String dyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.DYMC
     *
     * @mbggenerated
     */
    private String dymc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.XZGXF
     *
     * @mbggenerated
     */
    private Integer xzgxf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.XZCJ
     *
     * @mbggenerated
     */
    private Integer xzcj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZJLXMC
     *
     * @mbggenerated
     */
    private String zjlxmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ZJLXBM
     *
     * @mbggenerated
     */
    private String zjlxbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.TQFS
     *
     * @mbggenerated
     */
    private String tqfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ETL_DATE
     *
     * @mbggenerated
     */
    private Date etlDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.TYPE_ID
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ISOK
     *
     * @mbggenerated
     */
    private Integer isok;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.TASK_ID
     *
     * @mbggenerated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.DEAL_BY
     *
     * @mbggenerated
     */
    private Integer dealBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.DEAL_TM
     *
     * @mbggenerated
     */
    private Date dealTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.DEAL_ZT
     *
     * @mbggenerated
     */
    private Integer dealZt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ERR_CODE
     *
     * @mbggenerated
     */
    private String errCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.MOD_FLAG
     *
     * @mbggenerated
     */
    private String modFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.CODE_TYPE
     *
     * @mbggenerated
     */
    private String codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ISFR_TAG
     *
     * @mbggenerated
     */
    private Integer isfrTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.SRC_STATU
     *
     * @mbggenerated
     */
    private Integer srcStatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.DST_STATU
     *
     * @mbggenerated
     */
    private Integer dstStatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.DST_ISFR_TAG
     *
     * @mbggenerated
     */
    private Integer dstIsfrTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.XDR_SHXYM
     *
     * @mbggenerated
     */
    private String xdrShxym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.ORG_ID
     *
     * @mbggenerated
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.SFGK
     *
     * @mbggenerated
     */
    private Integer sfgk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.BZXR_CODE
     *
     * @mbggenerated
     */
    private String bzxrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.BZXR_NAME
     *
     * @mbggenerated
     */
    private String bzxrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_B_PJZC_T_SP_SXRMD.SXYW
     *
     * @mbggenerated
     */
    private String sxyw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ID
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ID
     *
     * @param id the value for TS_B_PJZC_T_SP_SXRMD.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.AJBS
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.AJBS
     *
     * @mbggenerated
     */
    public String getAjbs() {
        return ajbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.AJBS
     *
     * @param ajbs the value for TS_B_PJZC_T_SP_SXRMD.AJBS
     *
     * @mbggenerated
     */
    public void setAjbs(String ajbs) {
        this.ajbs = ajbs == null ? null : ajbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.AHQC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.AHQC
     *
     * @mbggenerated
     */
    public String getAhqc() {
        return ahqc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.AHQC
     *
     * @param ahqc the value for TS_B_PJZC_T_SP_SXRMD.AHQC
     *
     * @mbggenerated
     */
    public void setAhqc(String ahqc) {
        this.ahqc = ahqc == null ? null : ahqc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.FYDM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.FYDM
     *
     * @mbggenerated
     */
    public String getFydm() {
        return fydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.FYDM
     *
     * @param fydm the value for TS_B_PJZC_T_SP_SXRMD.FYDM
     *
     * @mbggenerated
     */
    public void setFydm(String fydm) {
        this.fydm = fydm == null ? null : fydm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.FYMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.FYMC
     *
     * @mbggenerated
     */
    public String getFymc() {
        return fymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.FYMC
     *
     * @param fymc the value for TS_B_PJZC_T_SP_SXRMD.FYMC
     *
     * @mbggenerated
     */
    public void setFymc(String fymc) {
        this.fymc = fymc == null ? null : fymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.GSBD
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.GSBD
     *
     * @mbggenerated
     */
    public BigDecimal getGsbd() {
        return gsbd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.GSBD
     *
     * @param gsbd the value for TS_B_PJZC_T_SP_SXRMD.GSBD
     *
     * @mbggenerated
     */
    public void setGsbd(BigDecimal gsbd) {
        this.gsbd = gsbd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.LARQ
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.LARQ
     *
     * @mbggenerated
     */
    public Date getLarq() {
        return larq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.LARQ
     *
     * @param larq the value for TS_B_PJZC_T_SP_SXRMD.LARQ
     *
     * @mbggenerated
     */
    public void setLarq(Date larq) {
        this.larq = larq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.BZXRLX
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.BZXRLX
     *
     * @mbggenerated
     */
    public Integer getBzxrlx() {
        return bzxrlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.BZXRLX
     *
     * @param bzxrlx the value for TS_B_PJZC_T_SP_SXRMD.BZXRLX
     *
     * @mbggenerated
     */
    public void setBzxrlx(Integer bzxrlx) {
        this.bzxrlx = bzxrlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.BZXRLXMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.BZXRLXMC
     *
     * @mbggenerated
     */
    public String getBzxrlxmc() {
        return bzxrlxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.BZXRLXMC
     *
     * @param bzxrlxmc the value for TS_B_PJZC_T_SP_SXRMD.BZXRLXMC
     *
     * @mbggenerated
     */
    public void setBzxrlxmc(String bzxrlxmc) {
        this.bzxrlxmc = bzxrlxmc == null ? null : bzxrlxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.DSRID
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.DSRID
     *
     * @mbggenerated
     */
    public String getDsrid() {
        return dsrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.DSRID
     *
     * @param dsrid the value for TS_B_PJZC_T_SP_SXRMD.DSRID
     *
     * @mbggenerated
     */
    public void setDsrid(String dsrid) {
        this.dsrid = dsrid == null ? null : dsrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.XM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.XM
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.XM
     *
     * @param xm the value for TS_B_PJZC_T_SP_SXRMD.XM
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.XBBM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.XBBM
     *
     * @mbggenerated
     */
    public Integer getXbbm() {
        return xbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.XBBM
     *
     * @param xbbm the value for TS_B_PJZC_T_SP_SXRMD.XBBM
     *
     * @mbggenerated
     */
    public void setXbbm(Integer xbbm) {
        this.xbbm = xbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.XBMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.XBMC
     *
     * @mbggenerated
     */
    public String getXbmc() {
        return xbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.XBMC
     *
     * @param xbmc the value for TS_B_PJZC_T_SP_SXRMD.XBMC
     *
     * @mbggenerated
     */
    public void setXbmc(String xbmc) {
        this.xbmc = xbmc == null ? null : xbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.SFZJHM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.SFZJHM
     *
     * @mbggenerated
     */
    public String getSfzjhm() {
        return sfzjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.SFZJHM
     *
     * @param sfzjhm the value for TS_B_PJZC_T_SP_SXRMD.SFZJHM
     *
     * @mbggenerated
     */
    public void setSfzjhm(String sfzjhm) {
        this.sfzjhm = sfzjhm == null ? null : sfzjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZPDZ
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZPDZ
     *
     * @mbggenerated
     */
    public String getZpdz() {
        return zpdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZPDZ
     *
     * @param zpdz the value for TS_B_PJZC_T_SP_SXRMD.ZPDZ
     *
     * @mbggenerated
     */
    public void setZpdz(String zpdz) {
        this.zpdz = zpdz == null ? null : zpdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.MZBM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.MZBM
     *
     * @mbggenerated
     */
    public String getMzbm() {
        return mzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.MZBM
     *
     * @param mzbm the value for TS_B_PJZC_T_SP_SXRMD.MZBM
     *
     * @mbggenerated
     */
    public void setMzbm(String mzbm) {
        this.mzbm = mzbm == null ? null : mzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.MZMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.MZMC
     *
     * @mbggenerated
     */
    public String getMzmc() {
        return mzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.MZMC
     *
     * @param mzmc the value for TS_B_PJZC_T_SP_SXRMD.MZMC
     *
     * @mbggenerated
     */
    public void setMzmc(String mzmc) {
        this.mzmc = mzmc == null ? null : mzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZZMMBM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZZMMBM
     *
     * @mbggenerated
     */
    public String getZzmmbm() {
        return zzmmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZZMMBM
     *
     * @param zzmmbm the value for TS_B_PJZC_T_SP_SXRMD.ZZMMBM
     *
     * @mbggenerated
     */
    public void setZzmmbm(String zzmmbm) {
        this.zzmmbm = zzmmbm == null ? null : zzmmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZZMMMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZZMMMC
     *
     * @mbggenerated
     */
    public String getZzmmmc() {
        return zzmmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZZMMMC
     *
     * @param zzmmmc the value for TS_B_PJZC_T_SP_SXRMD.ZZMMMC
     *
     * @mbggenerated
     */
    public void setZzmmmc(String zzmmmc) {
        this.zzmmmc = zzmmmc == null ? null : zzmmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.DZ
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.DZ
     *
     * @mbggenerated
     */
    public String getDz() {
        return dz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.DZ
     *
     * @param dz the value for TS_B_PJZC_T_SP_SXRMD.DZ
     *
     * @mbggenerated
     */
    public void setDz(String dz) {
        this.dz = dz == null ? null : dz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.DWMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.DWMC
     *
     * @mbggenerated
     */
    public String getDwmc() {
        return dwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.DWMC
     *
     * @param dwmc the value for TS_B_PJZC_T_SP_SXRMD.DWMC
     *
     * @mbggenerated
     */
    public void setDwmc(String dwmc) {
        this.dwmc = dwmc == null ? null : dwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.SFRDZXWY
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.SFRDZXWY
     *
     * @mbggenerated
     */
    public Integer getSfrdzxwy() {
        return sfrdzxwy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.SFRDZXWY
     *
     * @param sfrdzxwy the value for TS_B_PJZC_T_SP_SXRMD.SFRDZXWY
     *
     * @mbggenerated
     */
    public void setSfrdzxwy(Integer sfrdzxwy) {
        this.sfrdzxwy = sfrdzxwy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.RDZXDZ
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.RDZXDZ
     *
     * @mbggenerated
     */
    public String getRdzxdz() {
        return rdzxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.RDZXDZ
     *
     * @param rdzxdz the value for TS_B_PJZC_T_SP_SXRMD.RDZXDZ
     *
     * @mbggenerated
     */
    public void setRdzxdz(String rdzxdz) {
        this.rdzxdz = rdzxdz == null ? null : rdzxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.SFXZGXF
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.SFXZGXF
     *
     * @mbggenerated
     */
    public Integer getSfxzgxf() {
        return sfxzgxf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.SFXZGXF
     *
     * @param sfxzgxf the value for TS_B_PJZC_T_SP_SXRMD.SFXZGXF
     *
     * @mbggenerated
     */
    public void setSfxzgxf(Integer sfxzgxf) {
        this.sfxzgxf = sfxzgxf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.SFXZGXFMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.SFXZGXFMC
     *
     * @mbggenerated
     */
    public String getSfxzgxfmc() {
        return sfxzgxfmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.SFXZGXFMC
     *
     * @param sfxzgxfmc the value for TS_B_PJZC_T_SP_SXRMD.SFXZGXFMC
     *
     * @mbggenerated
     */
    public void setSfxzgxfmc(String sfxzgxfmc) {
        this.sfxzgxfmc = sfxzgxfmc == null ? null : sfxzgxfmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZZJGDM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZZJGDM
     *
     * @mbggenerated
     */
    public String getZzjgdm() {
        return zzjgdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZZJGDM
     *
     * @param zzjgdm the value for TS_B_PJZC_T_SP_SXRMD.ZZJGDM
     *
     * @mbggenerated
     */
    public void setZzjgdm(String zzjgdm) {
        this.zzjgdm = zzjgdm == null ? null : zzjgdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZSD
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZSD
     *
     * @mbggenerated
     */
    public String getZsd() {
        return zsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZSD
     *
     * @param zsd the value for TS_B_PJZC_T_SP_SXRMD.ZSD
     *
     * @mbggenerated
     */
    public void setZsd(String zsd) {
        this.zsd = zsd == null ? null : zsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.TZRMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.TZRMC
     *
     * @mbggenerated
     */
    public String getTzrmc() {
        return tzrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.TZRMC
     *
     * @param tzrmc the value for TS_B_PJZC_T_SP_SXRMD.TZRMC
     *
     * @mbggenerated
     */
    public void setTzrmc(String tzrmc) {
        this.tzrmc = tzrmc == null ? null : tzrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.CYM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.CYM
     *
     * @mbggenerated
     */
    public String getCym() {
        return cym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.CYM
     *
     * @param cym the value for TS_B_PJZC_T_SP_SXRMD.CYM
     *
     * @mbggenerated
     */
    public void setCym(String cym) {
        this.cym = cym == null ? null : cym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.CJSJ
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.CJSJ
     *
     * @mbggenerated
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.CJSJ
     *
     * @param cjsj the value for TS_B_PJZC_T_SP_SXRMD.CJSJ
     *
     * @mbggenerated
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZT
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZT
     *
     * @mbggenerated
     */
    public Integer getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZT
     *
     * @param zt the value for TS_B_PJZC_T_SP_SXRMD.ZT
     *
     * @mbggenerated
     */
    public void setZt(Integer zt) {
        this.zt = zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.SYS_TIME
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.SYS_TIME
     *
     * @mbggenerated
     */
    public Date getSysTime() {
        return sysTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.SYS_TIME
     *
     * @param sysTime the value for TS_B_PJZC_T_SP_SXRMD.SYS_TIME
     *
     * @mbggenerated
     */
    public void setSysTime(Date sysTime) {
        this.sysTime = sysTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.CJRBM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.CJRBM
     *
     * @mbggenerated
     */
    public String getCjrbm() {
        return cjrbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.CJRBM
     *
     * @param cjrbm the value for TS_B_PJZC_T_SP_SXRMD.CJRBM
     *
     * @mbggenerated
     */
    public void setCjrbm(String cjrbm) {
        this.cjrbm = cjrbm == null ? null : cjrbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.CJRMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.CJRMC
     *
     * @mbggenerated
     */
    public String getCjrmc() {
        return cjrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.CJRMC
     *
     * @param cjrmc the value for TS_B_PJZC_T_SP_SXRMD.CJRMC
     *
     * @mbggenerated
     */
    public void setCjrmc(String cjrmc) {
        this.cjrmc = cjrmc == null ? null : cjrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.SCRBM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.SCRBM
     *
     * @mbggenerated
     */
    public String getScrbm() {
        return scrbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.SCRBM
     *
     * @param scrbm the value for TS_B_PJZC_T_SP_SXRMD.SCRBM
     *
     * @mbggenerated
     */
    public void setScrbm(String scrbm) {
        this.scrbm = scrbm == null ? null : scrbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.SCRMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.SCRMC
     *
     * @mbggenerated
     */
    public String getScrmc() {
        return scrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.SCRMC
     *
     * @param scrmc the value for TS_B_PJZC_T_SP_SXRMD.SCRMC
     *
     * @mbggenerated
     */
    public void setScrmc(String scrmc) {
        this.scrmc = scrmc == null ? null : scrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZTMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZTMC
     *
     * @mbggenerated
     */
    public String getZtmc() {
        return ztmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZTMC
     *
     * @param ztmc the value for TS_B_PJZC_T_SP_SXRMD.ZTMC
     *
     * @mbggenerated
     */
    public void setZtmc(String ztmc) {
        this.ztmc = ztmc == null ? null : ztmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.READFLAG
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.READFLAG
     *
     * @mbggenerated
     */
    public Integer getReadflag() {
        return readflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.READFLAG
     *
     * @param readflag the value for TS_B_PJZC_T_SP_SXRMD.READFLAG
     *
     * @mbggenerated
     */
    public void setReadflag(Integer readflag) {
        this.readflag = readflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.LX
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.LX
     *
     * @mbggenerated
     */
    public Integer getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.LX
     *
     * @param lx the value for TS_B_PJZC_T_SP_SXRMD.LX
     *
     * @mbggenerated
     */
    public void setLx(Integer lx) {
        this.lx = lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.LXMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.LXMC
     *
     * @mbggenerated
     */
    public String getLxmc() {
        return lxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.LXMC
     *
     * @param lxmc the value for TS_B_PJZC_T_SP_SXRMD.LXMC
     *
     * @mbggenerated
     */
    public void setLxmc(String lxmc) {
        this.lxmc = lxmc == null ? null : lxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZXCJCS
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZXCJCS
     *
     * @mbggenerated
     */
    public Integer getZxcjcs() {
        return zxcjcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZXCJCS
     *
     * @param zxcjcs the value for TS_B_PJZC_T_SP_SXRMD.ZXCJCS
     *
     * @mbggenerated
     */
    public void setZxcjcs(Integer zxcjcs) {
        this.zxcjcs = zxcjcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZXCJCSMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZXCJCSMC
     *
     * @mbggenerated
     */
    public String getZxcjcsmc() {
        return zxcjcsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZXCJCSMC
     *
     * @param zxcjcsmc the value for TS_B_PJZC_T_SP_SXRMD.ZXCJCSMC
     *
     * @mbggenerated
     */
    public void setZxcjcsmc(String zxcjcsmc) {
        this.zxcjcsmc = zxcjcsmc == null ? null : zxcjcsmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.JLID
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.JLID
     *
     * @mbggenerated
     */
    public String getJlid() {
        return jlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.JLID
     *
     * @param jlid the value for TS_B_PJZC_T_SP_SXRMD.JLID
     *
     * @mbggenerated
     */
    public void setJlid(String jlid) {
        this.jlid = jlid == null ? null : jlid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.JSCRBM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.JSCRBM
     *
     * @mbggenerated
     */
    public String getJscrbm() {
        return jscrbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.JSCRBM
     *
     * @param jscrbm the value for TS_B_PJZC_T_SP_SXRMD.JSCRBM
     *
     * @mbggenerated
     */
    public void setJscrbm(String jscrbm) {
        this.jscrbm = jscrbm == null ? null : jscrbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.JSCRMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.JSCRMC
     *
     * @mbggenerated
     */
    public String getJscrmc() {
        return jscrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.JSCRMC
     *
     * @param jscrmc the value for TS_B_PJZC_T_SP_SXRMD.JSCRMC
     *
     * @mbggenerated
     */
    public void setJscrmc(String jscrmc) {
        this.jscrmc = jscrmc == null ? null : jscrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.YSCRBM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.YSCRBM
     *
     * @mbggenerated
     */
    public String getYscrbm() {
        return yscrbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.YSCRBM
     *
     * @param yscrbm the value for TS_B_PJZC_T_SP_SXRMD.YSCRBM
     *
     * @mbggenerated
     */
    public void setYscrbm(String yscrbm) {
        this.yscrbm = yscrbm == null ? null : yscrbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.YSCRMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.YSCRMC
     *
     * @mbggenerated
     */
    public String getYscrmc() {
        return yscrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.YSCRMC
     *
     * @param yscrmc the value for TS_B_PJZC_T_SP_SXRMD.YSCRMC
     *
     * @mbggenerated
     */
    public void setYscrmc(String yscrmc) {
        this.yscrmc = yscrmc == null ? null : yscrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.FDDBR
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.FDDBR
     *
     * @mbggenerated
     */
    public String getFddbr() {
        return fddbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.FDDBR
     *
     * @param fddbr the value for TS_B_PJZC_T_SP_SXRMD.FDDBR
     *
     * @mbggenerated
     */
    public void setFddbr(String fddbr) {
        this.fddbr = fddbr == null ? null : fddbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.XZSTARTDATE
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.XZSTARTDATE
     *
     * @mbggenerated
     */
    public Date getXzstartdate() {
        return xzstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.XZSTARTDATE
     *
     * @param xzstartdate the value for TS_B_PJZC_T_SP_SXRMD.XZSTARTDATE
     *
     * @mbggenerated
     */
    public void setXzstartdate(Date xzstartdate) {
        this.xzstartdate = xzstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.XZENDDATE
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.XZENDDATE
     *
     * @mbggenerated
     */
    public Date getXzenddate() {
        return xzenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.XZENDDATE
     *
     * @param xzenddate the value for TS_B_PJZC_T_SP_SXRMD.XZENDDATE
     *
     * @mbggenerated
     */
    public void setXzenddate(Date xzenddate) {
        this.xzenddate = xzenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.XZJCDATE
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.XZJCDATE
     *
     * @mbggenerated
     */
    public Date getXzjcdate() {
        return xzjcdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.XZJCDATE
     *
     * @param xzjcdate the value for TS_B_PJZC_T_SP_SXRMD.XZJCDATE
     *
     * @mbggenerated
     */
    public void setXzjcdate(Date xzjcdate) {
        this.xzjcdate = xzjcdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZXYJWH
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZXYJWH
     *
     * @mbggenerated
     */
    public String getZxyjwh() {
        return zxyjwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZXYJWH
     *
     * @param zxyjwh the value for TS_B_PJZC_T_SP_SXRMD.ZXYJWH
     *
     * @mbggenerated
     */
    public void setZxyjwh(String zxyjwh) {
        this.zxyjwh = zxyjwh == null ? null : zxyjwh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZXYJWHDW
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZXYJWHDW
     *
     * @mbggenerated
     */
    public String getZxyjwhdw() {
        return zxyjwhdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZXYJWHDW
     *
     * @param zxyjwhdw the value for TS_B_PJZC_T_SP_SXRMD.ZXYJWHDW
     *
     * @mbggenerated
     */
    public void setZxyjwhdw(String zxyjwhdw) {
        this.zxyjwhdw = zxyjwhdw == null ? null : zxyjwhdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.LXQK
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.LXQK
     *
     * @mbggenerated
     */
    public Integer getLxqk() {
        return lxqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.LXQK
     *
     * @param lxqk the value for TS_B_PJZC_T_SP_SXRMD.LXQK
     *
     * @mbggenerated
     */
    public void setLxqk(Integer lxqk) {
        this.lxqk = lxqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.LXQKMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.LXQKMC
     *
     * @mbggenerated
     */
    public String getLxqkmc() {
        return lxqkmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.LXQKMC
     *
     * @param lxqkmc the value for TS_B_PJZC_T_SP_SXRMD.LXQKMC
     *
     * @mbggenerated
     */
    public void setLxqkmc(String lxqkmc) {
        this.lxqkmc = lxqkmc == null ? null : lxqkmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.JTQX
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.JTQX
     *
     * @mbggenerated
     */
    public String getJtqx() {
        return jtqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.JTQX
     *
     * @param jtqx the value for TS_B_PJZC_T_SP_SXRMD.JTQX
     *
     * @mbggenerated
     */
    public void setJtqx(String jtqx) {
        this.jtqx = jtqx == null ? null : jtqx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.NL
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.NL
     *
     * @mbggenerated
     */
    public Integer getNl() {
        return nl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.NL
     *
     * @param nl the value for TS_B_PJZC_T_SP_SXRMD.NL
     *
     * @mbggenerated
     */
    public void setNl(Integer nl) {
        this.nl = nl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.AGE
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.AGE
     *
     * @mbggenerated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.AGE
     *
     * @param age the value for TS_B_PJZC_T_SP_SXRMD.AGE
     *
     * @mbggenerated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.DYID
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.DYID
     *
     * @mbggenerated
     */
    public String getDyid() {
        return dyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.DYID
     *
     * @param dyid the value for TS_B_PJZC_T_SP_SXRMD.DYID
     *
     * @mbggenerated
     */
    public void setDyid(String dyid) {
        this.dyid = dyid == null ? null : dyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.DYMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.DYMC
     *
     * @mbggenerated
     */
    public String getDymc() {
        return dymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.DYMC
     *
     * @param dymc the value for TS_B_PJZC_T_SP_SXRMD.DYMC
     *
     * @mbggenerated
     */
    public void setDymc(String dymc) {
        this.dymc = dymc == null ? null : dymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.XZGXF
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.XZGXF
     *
     * @mbggenerated
     */
    public Integer getXzgxf() {
        return xzgxf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.XZGXF
     *
     * @param xzgxf the value for TS_B_PJZC_T_SP_SXRMD.XZGXF
     *
     * @mbggenerated
     */
    public void setXzgxf(Integer xzgxf) {
        this.xzgxf = xzgxf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.XZCJ
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.XZCJ
     *
     * @mbggenerated
     */
    public Integer getXzcj() {
        return xzcj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.XZCJ
     *
     * @param xzcj the value for TS_B_PJZC_T_SP_SXRMD.XZCJ
     *
     * @mbggenerated
     */
    public void setXzcj(Integer xzcj) {
        this.xzcj = xzcj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZJLXMC
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZJLXMC
     *
     * @mbggenerated
     */
    public String getZjlxmc() {
        return zjlxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZJLXMC
     *
     * @param zjlxmc the value for TS_B_PJZC_T_SP_SXRMD.ZJLXMC
     *
     * @mbggenerated
     */
    public void setZjlxmc(String zjlxmc) {
        this.zjlxmc = zjlxmc == null ? null : zjlxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ZJLXBM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ZJLXBM
     *
     * @mbggenerated
     */
    public String getZjlxbm() {
        return zjlxbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ZJLXBM
     *
     * @param zjlxbm the value for TS_B_PJZC_T_SP_SXRMD.ZJLXBM
     *
     * @mbggenerated
     */
    public void setZjlxbm(String zjlxbm) {
        this.zjlxbm = zjlxbm == null ? null : zjlxbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.TQFS
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.TQFS
     *
     * @mbggenerated
     */
    public String getTqfs() {
        return tqfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.TQFS
     *
     * @param tqfs the value for TS_B_PJZC_T_SP_SXRMD.TQFS
     *
     * @mbggenerated
     */
    public void setTqfs(String tqfs) {
        this.tqfs = tqfs == null ? null : tqfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ETL_DATE
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ETL_DATE
     *
     * @mbggenerated
     */
    public Date getEtlDate() {
        return etlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ETL_DATE
     *
     * @param etlDate the value for TS_B_PJZC_T_SP_SXRMD.ETL_DATE
     *
     * @mbggenerated
     */
    public void setEtlDate(Date etlDate) {
        this.etlDate = etlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.TYPE_ID
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.TYPE_ID
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.TYPE_ID
     *
     * @param typeId the value for TS_B_PJZC_T_SP_SXRMD.TYPE_ID
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ISOK
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ISOK
     *
     * @mbggenerated
     */
    public Integer getIsok() {
        return isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ISOK
     *
     * @param isok the value for TS_B_PJZC_T_SP_SXRMD.ISOK
     *
     * @mbggenerated
     */
    public void setIsok(Integer isok) {
        this.isok = isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.TASK_ID
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.TASK_ID
     *
     * @mbggenerated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.TASK_ID
     *
     * @param taskId the value for TS_B_PJZC_T_SP_SXRMD.TASK_ID
     *
     * @mbggenerated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.DEAL_BY
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.DEAL_BY
     *
     * @mbggenerated
     */
    public Integer getDealBy() {
        return dealBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.DEAL_BY
     *
     * @param dealBy the value for TS_B_PJZC_T_SP_SXRMD.DEAL_BY
     *
     * @mbggenerated
     */
    public void setDealBy(Integer dealBy) {
        this.dealBy = dealBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.DEAL_TM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.DEAL_TM
     *
     * @mbggenerated
     */
    public Date getDealTm() {
        return dealTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.DEAL_TM
     *
     * @param dealTm the value for TS_B_PJZC_T_SP_SXRMD.DEAL_TM
     *
     * @mbggenerated
     */
    public void setDealTm(Date dealTm) {
        this.dealTm = dealTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.DEAL_ZT
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.DEAL_ZT
     *
     * @mbggenerated
     */
    public Integer getDealZt() {
        return dealZt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.DEAL_ZT
     *
     * @param dealZt the value for TS_B_PJZC_T_SP_SXRMD.DEAL_ZT
     *
     * @mbggenerated
     */
    public void setDealZt(Integer dealZt) {
        this.dealZt = dealZt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ERR_CODE
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ERR_CODE
     *
     * @mbggenerated
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ERR_CODE
     *
     * @param errCode the value for TS_B_PJZC_T_SP_SXRMD.ERR_CODE
     *
     * @mbggenerated
     */
    public void setErrCode(String errCode) {
        this.errCode = errCode == null ? null : errCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.MOD_FLAG
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.MOD_FLAG
     *
     * @mbggenerated
     */
    public String getModFlag() {
        return modFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.MOD_FLAG
     *
     * @param modFlag the value for TS_B_PJZC_T_SP_SXRMD.MOD_FLAG
     *
     * @mbggenerated
     */
    public void setModFlag(String modFlag) {
        this.modFlag = modFlag == null ? null : modFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.CODE_TYPE
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.CODE_TYPE
     *
     * @mbggenerated
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.CODE_TYPE
     *
     * @param codeType the value for TS_B_PJZC_T_SP_SXRMD.CODE_TYPE
     *
     * @mbggenerated
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ISFR_TAG
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ISFR_TAG
     *
     * @mbggenerated
     */
    public Integer getIsfrTag() {
        return isfrTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ISFR_TAG
     *
     * @param isfrTag the value for TS_B_PJZC_T_SP_SXRMD.ISFR_TAG
     *
     * @mbggenerated
     */
    public void setIsfrTag(Integer isfrTag) {
        this.isfrTag = isfrTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.SRC_STATU
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.SRC_STATU
     *
     * @mbggenerated
     */
    public Integer getSrcStatu() {
        return srcStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.SRC_STATU
     *
     * @param srcStatu the value for TS_B_PJZC_T_SP_SXRMD.SRC_STATU
     *
     * @mbggenerated
     */
    public void setSrcStatu(Integer srcStatu) {
        this.srcStatu = srcStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.DST_STATU
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.DST_STATU
     *
     * @mbggenerated
     */
    public Integer getDstStatu() {
        return dstStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.DST_STATU
     *
     * @param dstStatu the value for TS_B_PJZC_T_SP_SXRMD.DST_STATU
     *
     * @mbggenerated
     */
    public void setDstStatu(Integer dstStatu) {
        this.dstStatu = dstStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.DST_ISFR_TAG
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.DST_ISFR_TAG
     *
     * @mbggenerated
     */
    public Integer getDstIsfrTag() {
        return dstIsfrTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.DST_ISFR_TAG
     *
     * @param dstIsfrTag the value for TS_B_PJZC_T_SP_SXRMD.DST_ISFR_TAG
     *
     * @mbggenerated
     */
    public void setDstIsfrTag(Integer dstIsfrTag) {
        this.dstIsfrTag = dstIsfrTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.XDR_SHXYM
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.XDR_SHXYM
     *
     * @mbggenerated
     */
    public String getXdrShxym() {
        return xdrShxym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.XDR_SHXYM
     *
     * @param xdrShxym the value for TS_B_PJZC_T_SP_SXRMD.XDR_SHXYM
     *
     * @mbggenerated
     */
    public void setXdrShxym(String xdrShxym) {
        this.xdrShxym = xdrShxym == null ? null : xdrShxym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.ORG_ID
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.ORG_ID
     *
     * @mbggenerated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.ORG_ID
     *
     * @param orgId the value for TS_B_PJZC_T_SP_SXRMD.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.SFGK
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.SFGK
     *
     * @mbggenerated
     */
    public Integer getSfgk() {
        return sfgk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.SFGK
     *
     * @param sfgk the value for TS_B_PJZC_T_SP_SXRMD.SFGK
     *
     * @mbggenerated
     */
    public void setSfgk(Integer sfgk) {
        this.sfgk = sfgk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.BZXR_CODE
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.BZXR_CODE
     *
     * @mbggenerated
     */
    public String getBzxrCode() {
        return bzxrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.BZXR_CODE
     *
     * @param bzxrCode the value for TS_B_PJZC_T_SP_SXRMD.BZXR_CODE
     *
     * @mbggenerated
     */
    public void setBzxrCode(String bzxrCode) {
        this.bzxrCode = bzxrCode == null ? null : bzxrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.BZXR_NAME
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.BZXR_NAME
     *
     * @mbggenerated
     */
    public String getBzxrName() {
        return bzxrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.BZXR_NAME
     *
     * @param bzxrName the value for TS_B_PJZC_T_SP_SXRMD.BZXR_NAME
     *
     * @mbggenerated
     */
    public void setBzxrName(String bzxrName) {
        this.bzxrName = bzxrName == null ? null : bzxrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_B_PJZC_T_SP_SXRMD.SXYW
     *
     * @return the value of TS_B_PJZC_T_SP_SXRMD.SXYW
     *
     * @mbggenerated
     */
    public String getSxyw() {
        return sxyw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_B_PJZC_T_SP_SXRMD.SXYW
     *
     * @param sxyw the value for TS_B_PJZC_T_SP_SXRMD.SXYW
     *
     * @mbggenerated
     */
    public void setSxyw(String sxyw) {
        this.sxyw = sxyw == null ? null : sxyw.trim();
    }
}