package test.mybatis.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TsC500035JbxxZtsbFrjc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.QYBM
     *
     * @mbg.generated
     */
    private String qybm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.XDR
     *
     * @mbg.generated
     */
    private String xdr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.DMLX
     *
     * @mbg.generated
     */
    private String dmlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.DM
     *
     * @mbg.generated
     */
    private String dm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.FDDBRXM
     *
     * @mbg.generated
     */
    private String fddbrxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.FDDBRZJLX
     *
     * @mbg.generated
     */
    private String fddbrzjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.FDDBRZJHM
     *
     * @mbg.generated
     */
    private String fddbrzjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.GB
     *
     * @mbg.generated
     */
    private String gb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.ZCZB
     *
     * @mbg.generated
     */
    private BigDecimal zczb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.ZCZBBZ
     *
     * @mbg.generated
     */
    private String zczbbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.HYDM
     *
     * @mbg.generated
     */
    private String hydm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.LX
     *
     * @mbg.generated
     */
    private String lx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.JYFW
     *
     * @mbg.generated
     */
    private String jyfw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.ZS
     *
     * @mbg.generated
     */
    private String zs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.YZBM
     *
     * @mbg.generated
     */
    private String yzbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.DJJG
     *
     * @mbg.generated
     */
    private String djjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.CLRQ
     *
     * @mbg.generated
     */
    private Date clrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.BGRQ
     *
     * @mbg.generated
     */
    private Date bgrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.DJZT
     *
     * @mbg.generated
     */
    private String djzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.DJZTMC
     *
     * @mbg.generated
     */
    private String djztmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.HSFS
     *
     * @mbg.generated
     */
    private String hsfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.YYQXQ
     *
     * @mbg.generated
     */
    private Date yyqxq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.YYQXZ
     *
     * @mbg.generated
     */
    private Date yyqxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.HZRQ
     *
     * @mbg.generated
     */
    private Date hzrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.GSZCH
     *
     * @mbg.generated
     */
    private String gszch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.SJJHSJC
     *
     * @mbg.generated
     */
    private Date sjjhsjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.FLAG
     *
     * @mbg.generated
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.JYMC_ALTAFTER
     *
     * @mbg.generated
     */
    private String jymcAltafter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.JYLX
     *
     * @mbg.generated
     */
    private String jylx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.ETL_DATE
     *
     * @mbg.generated
     */
    private Date etlDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.SJ_SOURCE
     *
     * @mbg.generated
     */
    private String sjSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.GJFS
     *
     * @mbg.generated
     */
    private String gjfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.CL1
     *
     * @mbg.generated
     */
    private String cl1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.CL2
     *
     * @mbg.generated
     */
    private String cl2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.CL3
     *
     * @mbg.generated
     */
    private String cl3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.CL4
     *
     * @mbg.generated
     */
    private String cl4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.CL5
     *
     * @mbg.generated
     */
    private String cl5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.SFGK
     *
     * @mbg.generated
     */
    private String sfgk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.BGKYY
     *
     * @mbg.generated
     */
    private String bgkyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.ORG_ID
     *
     * @mbg.generated
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.ORG_NAME
     *
     * @mbg.generated
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.DFBM
     *
     * @mbg.generated
     */
    private String dfbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.DF_NAME
     *
     * @mbg.generated
     */
    private String dfName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.SJ_SOURCE_DESC
     *
     * @mbg.generated
     */
    private String sjSourceDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.IS_FR
     *
     * @mbg.generated
     */
    private String isFr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.ZT_LX
     *
     * @mbg.generated
     */
    private String ztLx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_C500035_JBXX_ZTSB_FRJC.ZT_DM
     *
     * @mbg.generated
     */
    private String ztDm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.QYBM
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.QYBM
     *
     * @mbg.generated
     */
    public String getQybm() {
        return qybm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.QYBM
     *
     * @param qybm the value for TS_C500035_JBXX_ZTSB_FRJC.QYBM
     *
     * @mbg.generated
     */
    public void setQybm(String qybm) {
        this.qybm = qybm == null ? null : qybm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.XDR
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.XDR
     *
     * @mbg.generated
     */
    public String getXdr() {
        return xdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.XDR
     *
     * @param xdr the value for TS_C500035_JBXX_ZTSB_FRJC.XDR
     *
     * @mbg.generated
     */
    public void setXdr(String xdr) {
        this.xdr = xdr == null ? null : xdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DMLX
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.DMLX
     *
     * @mbg.generated
     */
    public String getDmlx() {
        return dmlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DMLX
     *
     * @param dmlx the value for TS_C500035_JBXX_ZTSB_FRJC.DMLX
     *
     * @mbg.generated
     */
    public void setDmlx(String dmlx) {
        this.dmlx = dmlx == null ? null : dmlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DM
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.DM
     *
     * @mbg.generated
     */
    public String getDm() {
        return dm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DM
     *
     * @param dm the value for TS_C500035_JBXX_ZTSB_FRJC.DM
     *
     * @mbg.generated
     */
    public void setDm(String dm) {
        this.dm = dm == null ? null : dm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.FDDBRXM
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.FDDBRXM
     *
     * @mbg.generated
     */
    public String getFddbrxm() {
        return fddbrxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.FDDBRXM
     *
     * @param fddbrxm the value for TS_C500035_JBXX_ZTSB_FRJC.FDDBRXM
     *
     * @mbg.generated
     */
    public void setFddbrxm(String fddbrxm) {
        this.fddbrxm = fddbrxm == null ? null : fddbrxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.FDDBRZJLX
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.FDDBRZJLX
     *
     * @mbg.generated
     */
    public String getFddbrzjlx() {
        return fddbrzjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.FDDBRZJLX
     *
     * @param fddbrzjlx the value for TS_C500035_JBXX_ZTSB_FRJC.FDDBRZJLX
     *
     * @mbg.generated
     */
    public void setFddbrzjlx(String fddbrzjlx) {
        this.fddbrzjlx = fddbrzjlx == null ? null : fddbrzjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.FDDBRZJHM
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.FDDBRZJHM
     *
     * @mbg.generated
     */
    public String getFddbrzjhm() {
        return fddbrzjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.FDDBRZJHM
     *
     * @param fddbrzjhm the value for TS_C500035_JBXX_ZTSB_FRJC.FDDBRZJHM
     *
     * @mbg.generated
     */
    public void setFddbrzjhm(String fddbrzjhm) {
        this.fddbrzjhm = fddbrzjhm == null ? null : fddbrzjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.GB
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.GB
     *
     * @mbg.generated
     */
    public String getGb() {
        return gb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.GB
     *
     * @param gb the value for TS_C500035_JBXX_ZTSB_FRJC.GB
     *
     * @mbg.generated
     */
    public void setGb(String gb) {
        this.gb = gb == null ? null : gb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ZCZB
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.ZCZB
     *
     * @mbg.generated
     */
    public BigDecimal getZczb() {
        return zczb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ZCZB
     *
     * @param zczb the value for TS_C500035_JBXX_ZTSB_FRJC.ZCZB
     *
     * @mbg.generated
     */
    public void setZczb(BigDecimal zczb) {
        this.zczb = zczb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ZCZBBZ
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.ZCZBBZ
     *
     * @mbg.generated
     */
    public String getZczbbz() {
        return zczbbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ZCZBBZ
     *
     * @param zczbbz the value for TS_C500035_JBXX_ZTSB_FRJC.ZCZBBZ
     *
     * @mbg.generated
     */
    public void setZczbbz(String zczbbz) {
        this.zczbbz = zczbbz == null ? null : zczbbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.HYDM
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.HYDM
     *
     * @mbg.generated
     */
    public String getHydm() {
        return hydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.HYDM
     *
     * @param hydm the value for TS_C500035_JBXX_ZTSB_FRJC.HYDM
     *
     * @mbg.generated
     */
    public void setHydm(String hydm) {
        this.hydm = hydm == null ? null : hydm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.LX
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.LX
     *
     * @mbg.generated
     */
    public String getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.LX
     *
     * @param lx the value for TS_C500035_JBXX_ZTSB_FRJC.LX
     *
     * @mbg.generated
     */
    public void setLx(String lx) {
        this.lx = lx == null ? null : lx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.JYFW
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.JYFW
     *
     * @mbg.generated
     */
    public String getJyfw() {
        return jyfw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.JYFW
     *
     * @param jyfw the value for TS_C500035_JBXX_ZTSB_FRJC.JYFW
     *
     * @mbg.generated
     */
    public void setJyfw(String jyfw) {
        this.jyfw = jyfw == null ? null : jyfw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ZS
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.ZS
     *
     * @mbg.generated
     */
    public String getZs() {
        return zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ZS
     *
     * @param zs the value for TS_C500035_JBXX_ZTSB_FRJC.ZS
     *
     * @mbg.generated
     */
    public void setZs(String zs) {
        this.zs = zs == null ? null : zs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.YZBM
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.YZBM
     *
     * @mbg.generated
     */
    public String getYzbm() {
        return yzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.YZBM
     *
     * @param yzbm the value for TS_C500035_JBXX_ZTSB_FRJC.YZBM
     *
     * @mbg.generated
     */
    public void setYzbm(String yzbm) {
        this.yzbm = yzbm == null ? null : yzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DJJG
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.DJJG
     *
     * @mbg.generated
     */
    public String getDjjg() {
        return djjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DJJG
     *
     * @param djjg the value for TS_C500035_JBXX_ZTSB_FRJC.DJJG
     *
     * @mbg.generated
     */
    public void setDjjg(String djjg) {
        this.djjg = djjg == null ? null : djjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.CLRQ
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.CLRQ
     *
     * @mbg.generated
     */
    public Date getClrq() {
        return clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.CLRQ
     *
     * @param clrq the value for TS_C500035_JBXX_ZTSB_FRJC.CLRQ
     *
     * @mbg.generated
     */
    public void setClrq(Date clrq) {
        this.clrq = clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.BGRQ
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.BGRQ
     *
     * @mbg.generated
     */
    public Date getBgrq() {
        return bgrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.BGRQ
     *
     * @param bgrq the value for TS_C500035_JBXX_ZTSB_FRJC.BGRQ
     *
     * @mbg.generated
     */
    public void setBgrq(Date bgrq) {
        this.bgrq = bgrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DJZT
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.DJZT
     *
     * @mbg.generated
     */
    public String getDjzt() {
        return djzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DJZT
     *
     * @param djzt the value for TS_C500035_JBXX_ZTSB_FRJC.DJZT
     *
     * @mbg.generated
     */
    public void setDjzt(String djzt) {
        this.djzt = djzt == null ? null : djzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DJZTMC
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.DJZTMC
     *
     * @mbg.generated
     */
    public String getDjztmc() {
        return djztmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DJZTMC
     *
     * @param djztmc the value for TS_C500035_JBXX_ZTSB_FRJC.DJZTMC
     *
     * @mbg.generated
     */
    public void setDjztmc(String djztmc) {
        this.djztmc = djztmc == null ? null : djztmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.HSFS
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.HSFS
     *
     * @mbg.generated
     */
    public String getHsfs() {
        return hsfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.HSFS
     *
     * @param hsfs the value for TS_C500035_JBXX_ZTSB_FRJC.HSFS
     *
     * @mbg.generated
     */
    public void setHsfs(String hsfs) {
        this.hsfs = hsfs == null ? null : hsfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.YYQXQ
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.YYQXQ
     *
     * @mbg.generated
     */
    public Date getYyqxq() {
        return yyqxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.YYQXQ
     *
     * @param yyqxq the value for TS_C500035_JBXX_ZTSB_FRJC.YYQXQ
     *
     * @mbg.generated
     */
    public void setYyqxq(Date yyqxq) {
        this.yyqxq = yyqxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.YYQXZ
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.YYQXZ
     *
     * @mbg.generated
     */
    public Date getYyqxz() {
        return yyqxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.YYQXZ
     *
     * @param yyqxz the value for TS_C500035_JBXX_ZTSB_FRJC.YYQXZ
     *
     * @mbg.generated
     */
    public void setYyqxz(Date yyqxz) {
        this.yyqxz = yyqxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.HZRQ
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.HZRQ
     *
     * @mbg.generated
     */
    public Date getHzrq() {
        return hzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.HZRQ
     *
     * @param hzrq the value for TS_C500035_JBXX_ZTSB_FRJC.HZRQ
     *
     * @mbg.generated
     */
    public void setHzrq(Date hzrq) {
        this.hzrq = hzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.GSZCH
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.GSZCH
     *
     * @mbg.generated
     */
    public String getGszch() {
        return gszch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.GSZCH
     *
     * @param gszch the value for TS_C500035_JBXX_ZTSB_FRJC.GSZCH
     *
     * @mbg.generated
     */
    public void setGszch(String gszch) {
        this.gszch = gszch == null ? null : gszch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.SJJHSJC
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.SJJHSJC
     *
     * @mbg.generated
     */
    public Date getSjjhsjc() {
        return sjjhsjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.SJJHSJC
     *
     * @param sjjhsjc the value for TS_C500035_JBXX_ZTSB_FRJC.SJJHSJC
     *
     * @mbg.generated
     */
    public void setSjjhsjc(Date sjjhsjc) {
        this.sjjhsjc = sjjhsjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.FLAG
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.FLAG
     *
     * @mbg.generated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.FLAG
     *
     * @param flag the value for TS_C500035_JBXX_ZTSB_FRJC.FLAG
     *
     * @mbg.generated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.JYMC_ALTAFTER
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.JYMC_ALTAFTER
     *
     * @mbg.generated
     */
    public String getJymcAltafter() {
        return jymcAltafter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.JYMC_ALTAFTER
     *
     * @param jymcAltafter the value for TS_C500035_JBXX_ZTSB_FRJC.JYMC_ALTAFTER
     *
     * @mbg.generated
     */
    public void setJymcAltafter(String jymcAltafter) {
        this.jymcAltafter = jymcAltafter == null ? null : jymcAltafter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.JYLX
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.JYLX
     *
     * @mbg.generated
     */
    public String getJylx() {
        return jylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.JYLX
     *
     * @param jylx the value for TS_C500035_JBXX_ZTSB_FRJC.JYLX
     *
     * @mbg.generated
     */
    public void setJylx(String jylx) {
        this.jylx = jylx == null ? null : jylx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ID
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ID
     *
     * @param id the value for TS_C500035_JBXX_ZTSB_FRJC.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ETL_DATE
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.ETL_DATE
     *
     * @mbg.generated
     */
    public Date getEtlDate() {
        return etlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ETL_DATE
     *
     * @param etlDate the value for TS_C500035_JBXX_ZTSB_FRJC.ETL_DATE
     *
     * @mbg.generated
     */
    public void setEtlDate(Date etlDate) {
        this.etlDate = etlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.SJ_SOURCE
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.SJ_SOURCE
     *
     * @mbg.generated
     */
    public String getSjSource() {
        return sjSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.SJ_SOURCE
     *
     * @param sjSource the value for TS_C500035_JBXX_ZTSB_FRJC.SJ_SOURCE
     *
     * @mbg.generated
     */
    public void setSjSource(String sjSource) {
        this.sjSource = sjSource == null ? null : sjSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.GJFS
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.GJFS
     *
     * @mbg.generated
     */
    public String getGjfs() {
        return gjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.GJFS
     *
     * @param gjfs the value for TS_C500035_JBXX_ZTSB_FRJC.GJFS
     *
     * @mbg.generated
     */
    public void setGjfs(String gjfs) {
        this.gjfs = gjfs == null ? null : gjfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.CL1
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.CL1
     *
     * @mbg.generated
     */
    public String getCl1() {
        return cl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.CL1
     *
     * @param cl1 the value for TS_C500035_JBXX_ZTSB_FRJC.CL1
     *
     * @mbg.generated
     */
    public void setCl1(String cl1) {
        this.cl1 = cl1 == null ? null : cl1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.CL2
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.CL2
     *
     * @mbg.generated
     */
    public String getCl2() {
        return cl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.CL2
     *
     * @param cl2 the value for TS_C500035_JBXX_ZTSB_FRJC.CL2
     *
     * @mbg.generated
     */
    public void setCl2(String cl2) {
        this.cl2 = cl2 == null ? null : cl2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.CL3
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.CL3
     *
     * @mbg.generated
     */
    public String getCl3() {
        return cl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.CL3
     *
     * @param cl3 the value for TS_C500035_JBXX_ZTSB_FRJC.CL3
     *
     * @mbg.generated
     */
    public void setCl3(String cl3) {
        this.cl3 = cl3 == null ? null : cl3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.CL4
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.CL4
     *
     * @mbg.generated
     */
    public String getCl4() {
        return cl4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.CL4
     *
     * @param cl4 the value for TS_C500035_JBXX_ZTSB_FRJC.CL4
     *
     * @mbg.generated
     */
    public void setCl4(String cl4) {
        this.cl4 = cl4 == null ? null : cl4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.CL5
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.CL5
     *
     * @mbg.generated
     */
    public String getCl5() {
        return cl5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.CL5
     *
     * @param cl5 the value for TS_C500035_JBXX_ZTSB_FRJC.CL5
     *
     * @mbg.generated
     */
    public void setCl5(String cl5) {
        this.cl5 = cl5 == null ? null : cl5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.SFGK
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.SFGK
     *
     * @mbg.generated
     */
    public String getSfgk() {
        return sfgk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.SFGK
     *
     * @param sfgk the value for TS_C500035_JBXX_ZTSB_FRJC.SFGK
     *
     * @mbg.generated
     */
    public void setSfgk(String sfgk) {
        this.sfgk = sfgk == null ? null : sfgk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.BGKYY
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.BGKYY
     *
     * @mbg.generated
     */
    public String getBgkyy() {
        return bgkyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.BGKYY
     *
     * @param bgkyy the value for TS_C500035_JBXX_ZTSB_FRJC.BGKYY
     *
     * @mbg.generated
     */
    public void setBgkyy(String bgkyy) {
        this.bgkyy = bgkyy == null ? null : bgkyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ORG_ID
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.ORG_ID
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ORG_ID
     *
     * @param orgId the value for TS_C500035_JBXX_ZTSB_FRJC.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ORG_NAME
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.ORG_NAME
     *
     * @mbg.generated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ORG_NAME
     *
     * @param orgName the value for TS_C500035_JBXX_ZTSB_FRJC.ORG_NAME
     *
     * @mbg.generated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DFBM
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.DFBM
     *
     * @mbg.generated
     */
    public String getDfbm() {
        return dfbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DFBM
     *
     * @param dfbm the value for TS_C500035_JBXX_ZTSB_FRJC.DFBM
     *
     * @mbg.generated
     */
    public void setDfbm(String dfbm) {
        this.dfbm = dfbm == null ? null : dfbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DF_NAME
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.DF_NAME
     *
     * @mbg.generated
     */
    public String getDfName() {
        return dfName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.DF_NAME
     *
     * @param dfName the value for TS_C500035_JBXX_ZTSB_FRJC.DF_NAME
     *
     * @mbg.generated
     */
    public void setDfName(String dfName) {
        this.dfName = dfName == null ? null : dfName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.SJ_SOURCE_DESC
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.SJ_SOURCE_DESC
     *
     * @mbg.generated
     */
    public String getSjSourceDesc() {
        return sjSourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.SJ_SOURCE_DESC
     *
     * @param sjSourceDesc the value for TS_C500035_JBXX_ZTSB_FRJC.SJ_SOURCE_DESC
     *
     * @mbg.generated
     */
    public void setSjSourceDesc(String sjSourceDesc) {
        this.sjSourceDesc = sjSourceDesc == null ? null : sjSourceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.IS_FR
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.IS_FR
     *
     * @mbg.generated
     */
    public String getIsFr() {
        return isFr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.IS_FR
     *
     * @param isFr the value for TS_C500035_JBXX_ZTSB_FRJC.IS_FR
     *
     * @mbg.generated
     */
    public void setIsFr(String isFr) {
        this.isFr = isFr == null ? null : isFr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ZT_LX
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.ZT_LX
     *
     * @mbg.generated
     */
    public String getZtLx() {
        return ztLx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ZT_LX
     *
     * @param ztLx the value for TS_C500035_JBXX_ZTSB_FRJC.ZT_LX
     *
     * @mbg.generated
     */
    public void setZtLx(String ztLx) {
        this.ztLx = ztLx == null ? null : ztLx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ZT_DM
     *
     * @return the value of TS_C500035_JBXX_ZTSB_FRJC.ZT_DM
     *
     * @mbg.generated
     */
    public String getZtDm() {
        return ztDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_C500035_JBXX_ZTSB_FRJC.ZT_DM
     *
     * @param ztDm the value for TS_C500035_JBXX_ZTSB_FRJC.ZT_DM
     *
     * @mbg.generated
     */
    public void setZtDm(String ztDm) {
        this.ztDm = ztDm == null ? null : ztDm.trim();
    }
}